#!/usr/bin/env python3
"""V4 driver: lift -> signatures -> web renaming -> structuring -> eshop_decompile_v4.txt (+ functions.csv, call_graph.csv).
Names are purely structural (FUN_xxxxxxxx) unless analysis/v4/function_names.csv supplies evidence-backed names (phase B)."""
import sys, os, csv, pickle, time, collections, traceback, hashlib, multiprocessing as mp
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from v4_disasm import *
from v4_analyze import *
from v4_print import *

G = {}

def load_names():
    p = os.path.join(V4, 'function_names.csv'); names = {}
    if os.path.exists(p):
        for r in csv.DictReader(open(p)):
            names[int(r['address'], 16)] = (r['name'], r['confidence'])
    return names

def work(a):
    try:
        fi = G['firs'][a]
        rf = simplify(renamed_function(fi, G['sigs']))
        f = G['funcs'][a]; sg = G['sigs'][a]; m = G['m']
        nm = G['names'].get(a)
        fname = nm[0] if nm else 'FUN_%08x' % a
        hdr = ['// ==== Function @ %08x  file_off %06x  %s  size %#x  insns %d ====' % (a, m.va2off(a), 'THUMB' if f.thumb else 'ARM', f.end - a, len(f.insns)),
               '// id: FUN_%08x  name_confidence: %s  discovery: %s' % (a, nm[1] if nm else 'UNNAMED', G['why'].get(a, '?'))]
        cl = G['callers'].get(a)
        hdr.append('// callers: %d%s  callees: %d  sig: nparams=%d ret=%s%s%s' % (len(cl) if cl else 0, (' (' + ', '.join('%08x' % x for x in sorted(cl)[:4]) + (', ...' if len(cl) > 4 else '') + ')') if cl else ' (none direct; callback/vtable?)',
                   len(G['callees'].get(a, ())), sg.nparams, 'r0:r1' if sg.ret2 else 'r0' if sg.ret else 'void', ' stack_args>=%d' % sg.stack_args if sg.stack_args else '', ' NORETURN?' if sg.noret else ''))
        ss = G['strx'].get(a)
        if ss: hdr.append('// strings: ' + ' | '.join(ss[:4]))
        return a, '\n'.join(func_text(G['fm'], rf, sg, fname, f.thumb, hdr)), None
    except Exception as e:
        return a, '// ==== Function @ %08x ====\n// DECOMPILATION FAILED: %s\nvoid FUN_%08x(void);' % (a, repr(e)[:200], a), traceback.format_exc()

def main():
    t0 = time.time()
    m, d, funcs, entries = load_db()
    L = Lifter(m, d)
    firs = {e: FuncIR(f, L) for e, f in funcs.items()}
    print('lifted', time.time() - t0, file=sys.stderr, flush=True)
    eng = SigEngine(firs); eng.run(30)
    refs = pickle.load(open(os.path.join(V4, 'refs.pkl'), 'rb'))
    names = load_names()
    ctx = Ctx(m, entries, refs['strings'], {a: n for a, (n, c) in names.items()})
    why = pickle.load(open(os.path.join(V4, 'why.pkl'), 'rb')) if os.path.exists(os.path.join(V4, 'why.pkl')) else {}
    callers = eng.callers
    callees = collections.defaultdict(set)
    for a, fi in firs.items():
        for b in fi.blocks.values():
            for s, site in b.stmts:
                ss = s[2] if s[0] == 'pred' else s
                if ss[0] == 'call' and ss[1][0] == 'c': callees[a].add(ss[1][1])
            if b.term[0] == 'tail' and b.term[1][0] == 'c': callees[a].add(b.term[1][1])
    # strings per function
    sidx = {s[0]: s for s in refs['strings']}
    import bisect
    starts = sorted(sidx)
    strx = collections.defaultdict(list)
    for kind, fe, site, pool, v in refs['refs']:
        if kind == 'lit' and fe is not None:
            i = bisect.bisect_right(starts, v) - 1
            if i >= 0:
                s = sidx[starts[i]]
                span = s[3] * (2 if s[2] == 'utf16' else 1) + 1
                if v < s[0] + span:
                    t = s[4].replace('\n', '\\n')[:48]
                    if t not in strx[fe]: strx[fe].append(t)
    G.update(firs=firs, funcs=funcs, sigs=eng.sigs, m=m, names=names, why=why, callers=callers, callees=callees, strx=strx, fm=Fmt(ctx, eng.sigs))
    addrs = sorted(funcs)
    with mp.get_context('fork').Pool(4) as pool:
        res = pool.map(work, addrs, chunksize=64)
    fails = [(a, tb) for a, t, tb in res if tb]
    out = os.path.join(os.path.dirname(V4), '..', 'eshop_decompile_v4.txt')
    with open(out, 'w') as fh:
        fh.write('// eshop_decompile_v4.txt - structural reconstruction of code_decompressed.bin (sha256 %s)\n' % hashlib.sha256(m.code).hexdigest())
        fh.write('// Generated by analysis/v4_decompile.py. Pseudo-C: not buildable. FUN_ names are address ids; see analysis/v4/pass_log.md\n\n')
        for a, t, tb in res: fh.write(t + '\n\n\n')
    with open(os.path.join(V4, 'functions.csv'), 'w', newline='') as fh:
        w = csv.writer(fh); w.writerow(['address', 'file_offset', 'mode', 'size', 'insns', 'discovery', 'nparams', 'returns', 'stack_args', 'n_callers', 'n_callees', 'blocks', 'unresolved_indirect', 'noreturn'])
        for a in addrs:
            f = funcs[a]; sg = eng.sigs[a]; fi = firs[a]
            ind = sum(1 for b in fi.blocks.values() if b.term[0] in ('ibr', 'itail')) + sum(1 for b in fi.blocks.values() for s, _ in b.stmts if (s[2] if s[0] == 'pred' else s)[0] == 'call' and (s[2] if s[0] == 'pred' else s)[1][0] != 'c')
            w.writerow(['%08x' % a, '%x' % m.va2off(a), 'T' if f.thumb else 'A', f.end - a, len(f.insns), why.get(a, ''), sg.nparams, 'r0:r1' if sg.ret2 else 'r0' if sg.ret else 'void', sg.stack_args, len(callers.get(a, ())), len(callees.get(a, ())), len(fi.blocks), ind, int(sg.noret)])
    with open(os.path.join(V4, 'call_graph.csv'), 'w', newline='') as fh:
        w = csv.writer(fh); w.writerow(['caller', 'callee'])
        for a in addrs:
            for c in sorted(callees.get(a, ())): w.writerow(['%08x' % a, '%08x' % c])
    print('functions', len(addrs), 'failed', len(fails), 'time', time.time() - t0, file=sys.stderr)
    for a, tb in fails[:5]: print(hex(a), tb, file=sys.stderr)
    pickle.dump(fails, open(os.path.join(V4, 'fails.pkl'), 'wb'))

if __name__ == '__main__': main()
